name: Node.js Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout

      - name: Set up Node.js
        uses: actions/setup-node
        with:
          node-version: '22'

      - name: Run test script
        run: node test.js